name: SSH into remote server

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v4
      - name: SSH into remote server and run echo hello world
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            touch hi_there.txt
            echo "Hello World" > hi_there.txt
